always-bypass: false
always-bypass-if-not-negative: false
enforced-mythic-type: []

database:
  # (scheme)://(host):(port)/(database)
  # Keep the line commented out unless you get an obvious error message indicating that the driver was not found.
  # Default driver (net.azisaba.lifepvelevel.libs.org.mariadb.jdbc.Driver) points to the bundled MariaDB driver in the jar.
  #driver: net.azisaba.lifepvelevel.libs.org.mariadb.jdbc.Driver

  # change to jdbc:mysql if you want to use MySQL instead of MariaDB
  scheme: jdbc:mariadb
  hostname: localhost
  port: 3306
  name: lifepvelevel
  username: lifepvelevel
  password: lifepvelevel
  properties:
    useSSL: true
    verifyServerCertificate: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    cachePrepStmts: true
    useServerPrepStmts: true # use server-side prepared statements for performance boost
    socketTimeout: 30000 # milliseconds
    useLocalSessionState: true
    rewriteBatchedStatements: true
    maintainTimeStats: false
