name: LifePvELevel
version: @version@
main: net.azisaba.lifepvelevel.SpigotPlugin
api-version: 1.15
depend:
  - TAB
  - TAB-BukkitBridge
  - LoreEditor
  - ItemStash
  - MythicMobs
softdepend:
  - Statz
  - mcMMO
  - MyPet
commands:
  pvelevel:
    permission: lifepvelevel.command.pvelevel
  pvelevelitem:
    permission: lifepvelevel.command.pvelevelitem
  resetpvelevel:
    permission: lifepvelevel.command.resetpvelevel
  pvelevelranking:
    permission: lifepvelevel.command.pvelevelranking
    aliases: [pvelevelrank]
  checkpvelevelboost:
    permission: lifepvelevel.command.checkpvelevelboost
    aliases: [checkpveboost, cplb, cpb]
  givepvelevelboostitem:
    permission: lifepvelevel.command.givepvelevelboostitem
permissions:
  lifepvelevel.command.pvelevel:
    description: Allows the player to use /pvelevel
    default: true
  lifepvelevel.command.pvelevel.admin:
    description: Allows the player to use arguments for /pvelevel
    default: false
  lifepvelevel.command.pvelevelitem:
    description: Allows the player to use /pvelevelitem
    default: false
  lifepvelevel.command.checkpvelevelboost:
    description: Allows the player to use /checkpvelevelboost
    default: true
  lifepvelevel.command.givepvelevelboostitem:
    description: Allows the player to use /givepvelevelboostitem
    default: op
  lifepvelevel.bypass_level:
    description: Allows the player to bypass the level requirement
    default: false
  lifepvelevel.bypass_boost_limit:
    description: Allows the player to bypass the boost cap
    default: false
